### ISSUE TITLE
Version Tags

### ISSUE THREAD

**Issue by adius** [3dcitydb/3dcitydb#1]
It would be great if you could add version tags (at least for the last version)!

**Comment by clausnagel** [comment]
Hi Adrian,

Thanks for your comment. We have not yet released a version from this repository. The release is scheduled for March. We will add a version tag then.

Cheers,
Claus

**Comment by adius** [comment]
…and what about the one included in the 1.6.0 version of the 3dcitydb-importer-exporter

**Comment by clausnagel** [comment]
Just tagged version 3.0 of the 3D City Database.

The SQL scripts of the previous version 2.1 of the 3D City Database are included in the repositories of the previous version 1.6 of the Importer/Exporter:
* [importer-exporter-postgis](https://github.com/3dcitydb/importer-exporter-postgis)
* [importer-exporter-oracle](https://github.com/3dcitydb/importer-exporter-oracle)

We currently do not maintain tags for the previous version of the 3D City Database and the Importer/Exporter because we have not released from these repositories yet. This might change if we need to issue a bugfix release. And creating bugfixes for the previous version is the only purpose of both repositories.

The new Importer/Exporter for version 3.0 of the 3D City Database is developed and tagged here:
* [importer-exporter](https://github.com/3dcitydb/importer-exporter)
