### ISSUE TITLE
Drop the UNIQUE constraint on the gmlid column

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#100]
We want to use the `feature` table to store mulitple versions of the same city objects, and the `gmlid` column values may not always keep UNIQUE.  The UNIQUE constraint must be dropped. 

Additionally, in the current v5 schema, the following indexes are defined:

```
CREATE INDEX feature_gmlid_btr ON citydb.feature  ( gmlid );
CREATE INDEX feature_identifier ON citydb.feature  ( identifier );
```
shouldn't the index be defined on two columns like with the current v4 schema?
```
CREATE INDEX feature_gmlid_btr ON citydb.feature  ( gmlid, gmlid_namespace );
CREATE INDEX feature_identifier ON citydb.feature  ( identifier, identifier_namespace );
```

**Comment by clausnagel** [comment]
+1 for dropping the UNIQUE constraint

I think an index on `( identifier, identifier_namespace )` makes sense. Regarding the gmlid, I am not sure why we should continue to have a `gmlid_namespace` column at all. I would prefer dropping it.

Btw, gmlid must be renamed to featureid (or feature_id). See fig. 19 [CityGML 3.0 spec](https://docs.ogc.org/is/20-010/20-010.html#toc30).

**Comment by yaozhihang** [comment]
Fully agree. The name `featureid` is good. `feature_id` looks like a bigint FK column.

**Comment by muratkendir** [comment]
Well, i think this is one of the most important thing for entire database upgrade process. I have designed basic principle of upsert scripts over this concept, which expects gmlid column as unique. During some upgrades (for exp. Tokio, Ingolstadt), i noticed duplicated gmlid's in cityobject table and simply removed them. By the way, i don't want to start a conceptual/abstract discussion about that, but also want to discuss about that from a widen perspective: What is the meaning of keeping a (non-unique / but "identifier" ?) column in cityobject table? I think we should discuss it.

By the way, as i know that featureID and gmlid are different things. featureID is actually created as id in the feature table and belongs to AbstractFeature class, but gmlid belongs to AnyFeature which is super class of AbstractFeature.

**Comment by clausnagel** [comment]
@muratkendir, you cannot assume unique gmlids in v4 because there can be multiple features with the same gmlid but at different timestamps (so, they differ in creation_date and termination_date). We should not require unique gmlids in v5 for the same reason. Note that gmlids are not globally unique per definition, but only within one and the same dataset.

If your upsert scripts require unique gmlids, then we need to document this fact. Users must ensure this requirement if they want to use the scripts.

featureID is mapped to gmlid in the [draft GML encoding of CityGML 3.0](https://github.com/opengeospatial/CityGML-3.0Encodings/tree/master/CityGML). So, yes, they are the same. My point is that we should avoid GML-specific column names. The names should follow the conceptual model and not a specific encoding wherever possible.

**Comment by muratkendir** [comment]
I tried to avoid to make personal assumptions, but maybe you have right. Please give me some time to test available datasets and check standardization documents again to refresh my mind. I am confused, because if you have right about featureID and gmlid, then you maybe wrong about "unique identifier" convention, regarding to this definition:
[link to FeatureID > ID definition image](https://drive.google.com/file/d/1c2AW-IhF-8zKSdKoXmLXrp0drgiR5cvn/view?usp=sharing)
[link to FeatureID > ID](https://docs.ogc.org/is/20-010/20-010.html#ID-section)

**Comment by clausnagel** [comment]
Please check chapter 6.2.1 of the CityGML 3 CM spec. Here is an excerpt:

> The featureID is unique within the same CityGML dataset, but it is generally recommended to use globally unique identifiers like UUID values or identifiers maintained by an organization such as a mapping agency. Providing globally unique and stable identifiers for the identifier attribute is recommended. This means these identifiers should remain stable over the lifetime of the real-world object.

And also check chapter 6.1.2 of the draft GML encoding (here as [PDF](https://github.com/opengeospatial/CityGML-3.0Encodings/blob/master/CityGML/21-006.pdf)). 

I would like to close the discussion about renaming gmlid here now because it's obvious that we need to do it. Zhihang suggested to use objectid rather than featureid - that's even a better name.

**Comment by muratkendir** [comment]
I get particularly different meaning (about Universal Unique ID's) from the quotation that you written, but i agree about to close discussion a least for now.

**Comment by clausnagel** [comment]
The references were only to illustrate the mapping of featureID to gml:id.

The recommendation of using UUIDs in the spec cannot be translated into having a UNIQUE constraint on the objectid column. That's simply because we can a feature with the same objectid at multiple timestamps (see Zhihang's and my comments above).

**Comment by muratkendir** [comment]
Is there any mechanism to check / avoid duplicated rows?
