### ISSUE TITLE
Drop the "xml_source" column in the feature table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#101]
I think the `xml_source` column can be dropped. It is never used (at least in Importer/Exporter) in the current citydb v4.

**Comment by clausnagel** [comment]
Hm, good point. The column was always meant to store a "static snapshot" of the feature that could be directly returned instead of having to dynamically rebuild the feature from multiple nested tables using expensive joins. For example, WFS responses could be extremely fast if they would just return the static snapshot. But then, if you use the same WFS interface to update attributes of a feature in the database, you want to get the updated feature in a subsequent query and not the previous snapshot, of course. That's at least one reason why I'm also not aware that this column is used in practice. 

And which data format would you use to store the snapshot? GML? JSON? glTF because you want to use it for visualization?

I am in favour of dropping the column unless we have a clear and well-defined use case. We can still add it again later or move it to its own table.

**Comment by muratkendir** [comment]
@yaozhihang you have right, it is never used, but you may remember that we have copied addresses into feature table.
In upsert scripts, i stored xal_source columns into two different columns:

1. feature > xml_source (text)
2. property > val_xml (xml)

Since val_xml column created as xml data type, it need to parse xml to store/copy it. I don't know what can be done with XML Parse errors. It is a bit risky, but will be beneficial too, i agree that.
There was already a comment for the xml_source column:
[link](https://drive.google.com/file/d/1sillb2TKgOCHkDJOTyjzcmCCyeAfw_Cy/view?usp=sharing)

**Comment by clausnagel** [comment]
val_xml does not really make sense to me. We will not just have XML data as input for the 3DCityDB. If we need such a generic value column, it should rather be a clob.

**Comment by yaozhihang** [comment]
yes, for the current use case for storing the raw xalAddress content, the text/clob type should be sufficient enough.

**Comment by muratkendir** [comment]
Actually, i don't suggest to drop any columns at this moment. Even it is useless / always empty, it should be kept till to decide a "total revision". The reason for that is upsert scripts already creating these columns and populates them. Main advantage of keeping columns will gain enough time to focus import/export tool developments. I think, maybe we need to focus needed / addable columns. 
@clausnagel  I made some tests with xml type data and i had successfully derived some parts of addresses using postgresql xml functions. So, maybe val_xml column can be useful to derive missing parts from the xml sources.

**Comment by clausnagel** [comment]
My preferred approach would be different: start with a minimum number of columns and only add additional columns when really required.

And how do you populate val_xml if your input dataset is CityJSON?

**Comment by yaozhihang** [comment]
How about rename `val_xml`  -> `val_source` and use text/clob type for storing json and xml data? Also, we can add a new column `val_source_mime_type` to indicate the type of the data. This should be generic enough

**Comment by muratkendir** [comment]
@clausnagel If input dataset is CityJSON, then we can use val_complex column, it is in json data type.

@yaozhihang if we will convert val_xml into text data type, then it would be just like xml_source. By the way, using xml sources from text or similarly using json sources from text will make us unable to use postgresql's native json/xml functions.

**Comment by clausnagel** [comment]
@muratkendir, val_complex was initially meant to store complex data types (i.e., values of attributes that cannot be stored in one row of the property table). It should have long be removed from the schema because we decided to map complex data types to multiple rows. So I wonder why this column still exists?

How to store original snippets of input datasets still needs more discussion. The most generic solution would be to keep such snippets independent from a specific encoding. For example, we could decide to use JSON as datatype for such a generic column _plus_ we would need mapping rules for mapping CityGML or CityJSON snippets to this generic JSON representation. This would allow us to re-generate CityGML or CityJSON snippets from the internal representation when we export data. This really needs more thoughts.

**Comment by muratkendir** [comment]
>  The most generic solution would be to keep such snippets independent from a specific encoding.
I am not agree with this statement, i mean if it is really generic solution, then maybe we need to re-evaluate to use snippets with their original data types to get most benefits from postgresql. For exp. assume that we decided to store all height measurements of buildings as text/varchar in database, but in json format. Then we won't be able use JSON/JSONB indexing capabilities of postgresql, which may change query performance dramatically.

**Comment by clausnagel** [comment]
@muratkendir, we are talking about different things which makes the discussion a bit demanding. The default case is that attribute values are stored in the predefined val_* columns and _not_ in val_xml. This is only meant to store a static representation taken 1:1 from the dataset. And then thinking about making this representation independent from a specific encoding of the _input dataset_ (not _database type_) makes sense.

But I agree with @yaozhihang to use val_source (text/clob) and val_source_mime_type for now.
