### ISSUE TITLE
Drop the "name", "name_codespace", "description" columns from the appearance and surface_data tables

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#109]
Drop these three columns for the alpha release. If we want to re-add the three columns, we need thought about making the `appearance` and `surface_data` tables to be subclass fo the `feature` table to gain a consistent structure for storing AbstractFeatures.

**Comment by clausnagel** [comment]
Some thoughts to explain the issue: There can be multiple `gml:name` attributes for one feature. So, we would again need a delimiter to store them all in one `name` column. But we wanted to get rid of this mechanism with the 3DCityDB v5. The names cannot be stored in the `property` table because neither `appearance` nor `surface_data` are linked to `feature`. And we have to carefully consider whether we really want to store appearances and surface data in the `feature` table.
