### ISSUE TITLE
Purpose of "space_or_boundary_type" column?

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#113]
What is the purpose of the `space_or_boundary_type` column in the `feature` table? And if we need it, shouldn't it rather be moved to `objectclass`?

**Comment by yaozhihang** [comment]
_name of the most specific CityGML abstract space or space boundary class (e.g. AbstractOccupiedSpace)_ 

accroding to this doc
https://github.com/tum-gis/3dcitydb-v5/blob/master/docs/meeting_recordings/2021_10_19_3DCityDB_Version_5.0_Kolbe.xlsx

**Comment by clausnagel** [comment]
I see the following issues:

1. We do not just store spaces and space boundaries in `feature`. 
2. The object type implicitly follows from the linked entry in `objectclass`. We also map the class hierarchy to `objectclass`.
3. If we need to store the type name, then it should also be stored in `objectclass` rather than redundantly with every instance in `feature`. This is how we use `objectclass` in 3DCityDB v4 as well.

This needs more discussion.

**Comment by muratkendir** [comment]
I just used objectclass table and values to fill space_or_boundary_type column while working with upgrade scripts. On the other hand, i think it is not a super class/category of objectclass, moreover it is more likely a new tag to differ features regarding to their behaviors in reality. Accepting this concept as a tag rather than hierarchical order/category may give an advantage of flexibility of creating combinations with objectclasses and space_or_boundary_type information. For example, "AuxilaryTrafficSpace" will be normally accepted as "AbstractUnoccpiedSpace", but will we handle same feature as "OccupiedSpace" for different kind of domains/use cases such as UAV's, animals or auto-driven vehicles in the future? Of course, this is also interesting topic and need to be discussed more about it.
