### ISSUE TITLE
drop the "is_toplevel" column from feature table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#120]
There is already a "is_toplevel" column in the `objectclass` table. I think we can avoid such redundancy.

**Comment by clausnagel** [comment]
`<<TopLevelFeatureType>>` is a predefined stereotype from the CityGML 3.0 CM, and the purpose of the `is_toplevel` column currently is just to make this information available. So, I also think that we only need to store this information once. And `objectclass` seems to be the better place because we then have a nice separation between storing concrete feature instances in `feature` and information about the conceptual model in `objectclass` (and `aggregation_info` etc.).

In general, I also think that storing the feature hierarchy would really make sense. "Feature hierachy" (in contrast to "class hierarchy") would really be the hierarchy of concrete feature instances (like "Window A" is a child of "WallSurface B" is a child of "Building C"). Issue #123 goes into this direction and could even be extended to also store the `parent_feature_id`. But I would decouple this dicussion from the issue here.
