### ISSUE TITLE
add column "root_feature_id" to the property table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#123]
The new `root_feature_id` should be a FK pointing to the corresponding top-level feature. This column would help for speeding up the export and delete process by avoiding recursive joins. Note that we should not move this column to the `feature` table, because a nested feature can be shared by multiple top-level features via XLinks.

**Comment by clausnagel** [comment]
I support the idea of having easy access to the root feature of a feature hierarchy. But I would even see the need for having access to the direct parent in addition.

It does not feel right to have this information in `property` but not in `feature`. I see your point, but maybe we can also solve it differently? Because we need the information about the root / parent feature only once. It we move this to a column in property, it would be stored multiple times for a single feature (as many times as the feature has properties). And what if we want to later add an attribute to this feature (e.g. via a WFS Update statement). How would this update statement know which values to use for the root / parent feature? It would first have to make a select on `property` - again, doesn't feel right.

**Comment by clausnagel** [comment]
Let's discuss in #126, so closing this issue now.
