### ISSUE TITLE
rename "feature_id" to "parent_feature_id" in the property table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#125]
Since we introduce the column `root_feature_id` (see #123) in the property table, wouldn't be better to rename `feature_id` > `parent_feature_id`? That would be more intuitive for building the "Feature hierarchy". See the comment:
https://github.com/3dcitydb/3dcitydb/issues/120#issuecomment-1150827820

**Comment by clausnagel** [comment]
I don't think so?

Assume we have a "Window A" with a name attribute. And "Window A" is a child of "WallSurface B", and "WallSurface B" is a child of "Building C".

When we store the name attribute in `property`, then:

- `feature_id` should point to the entry of "Window A",
- `parent_feature_id` should point to the entry of "WallSurface B",
- `root_feature_id` should point to the entry of "Building C".

So, in my understanding, we cannot rename `feature_id` to `parent_feature_id`.

**Comment by yaozhihang** [comment]
hm, what about this case: We have a "WallSurface A" with a name attribute. And "WallSurface A" is shared by "BuildingPart B" and "BuildingPart C". Their root feature is "Building D"

 now in `property` table:

- `feature_id` points to the entry of "WallSurface A"
- `root_feature_id` points to the entry of "Building D"
- `parent_feature_id` ?

**Comment by clausnagel** [comment]
move `root_feature_id` and `parent_feature_id` to the `feature` table and make it an array?

**Comment by yaozhihang** [comment]
Alternatively. I could readd the `feature_relation` table to includethe three columns `child_id, parent_id, root_id` ?

**Comment by clausnagel** [comment]
Yes, an additional table is also an alternative I thought about. Would rather name it `feature_hierarchy`, but that's just a minor thing :-) We need consensus on this, so maybe something for after the alpha release?

**Comment by yaozhihang** [comment]
`feature_hierarchy` looks good. Adding this table is simple, I would like to add this into the alpha release, because it is needed for implementing the delete and envelope functions afte the alpha release.

**Comment by muratkendir** [comment]
I think we can re-add feature_relation table and if we need to avoid recursive queries, then maybe we can add "root_feature" column as addition to "from_feature" and "to_feature". 
The reason for not selecting "hierarchy" as table name is that we can also store bidirectional relations or any kind of relation then hierarchy. Hierarchy is only one type unidirectional relation.
By the way, we have still an option to generate and store "root_id"s in materialized views too. I mean, if a window->isPartOf->Wall and a wall->isPartOf->building, then we can generate root_id for window feature by tracking relations, we can store them as materialized view and join into any table whenever we want to use. If any data can automatically generated by given other data, why we need to store it?

**Comment by clausnagel** [comment]
I think `feature_hierarchy` fits quite well because we typically will have a single top-level feature as root with its nested children. And we need to be able to quickly query the (transitive) parents and children for a given feature in this hierarchy (e.g., when clicking on a window in a viewer, we want to know the parent wall, building part, building, etc.; see examples above). And the table is designed such that a given feature can participate in more than one hierarchy. So, I guess the table is flexible enough for the scenarios we need even beyond the CityGML data model.

Since the table is included in the alpha release, I close this issue now. If we still need changes to the `feature_hierarchy` table, they should be discussed in separate issues.
