### ISSUE TITLE
How to store non-feature objects?

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#126]
In CityGML, we have objects (i.e., things having an identifier) that are not features, such as `ImplicitGeometry`. Also ADEs can define such non-feature objects (e.g., `WeatherData` in Energy ADE). In the 3DCityDB v4, we register the corresponding classes in `objectclass` and store the object instances in `cityobject`.

I guess we have to handle it the same way in v5 (i.e., register the class in `objectclass` and store instances in `feature`). Just wanted to make sure that this is common sense. And if so, woudn't `object` be a better table name than `feature`?

**Comment by clausnagel** [comment]
I mean we could also use `cityobject` as table name again. Not to relate the table to the `AbstractCityObject` class in CityGML. But rather because in the "city db" we store "city objects" :-) But it might also be confusing...

We could go with `feature` for the alpha release and discuss/decide this later.

**Comment by gioagu** [comment]
Shouldn't we simply call the table OBJECT, instead of feature?

**Comment by muratkendir** [comment]
I think all existing "object" words should be changed with feature. In this kind of situations, i try always to select most conventional, most well-known definitions. As i explained in (#131), lots of GIS companies uses "feature" (or FID) instead of "object" (or OID). 

The reason behind of that is, every single feature somehow represented in 2D/3D map or simply joined to a spatial data. For example weather data should at least one location to represent location of weather stations, sensors or simply joined to a spatial data which may represent center point of a administrative area. Otherwise there is no meaning of storing a CSV-like sheet directly (without spatial information) in CityDB or CityGML. And all data comes from these sensors should be considered as "property" with their namespace and names.

Namespace and name combination is providing very flexible method to store ADE's with also Codelist + Codelist Entry tables. (I think any ADE can also implement class - function - usage concept with their own codelists. These three columns don't need to be reserved for only for predefined CityGML features.) As addition, we need also prepare a "Reserved Namespaces" document to avoid using same namespaces in ADE's.

**Comment by clausnagel** [comment]
@muratkendir, the point is that we can define _object types_ that are not features but still have an identity, attributes (including spatial ones) and associations. In UML, object types are typically marked using the `<<Type>>` stereotype (or have no stereotype at all). _Feature types_, in contrast, are marked as `<<FeatureType>>`.  This is inline with OGC and GML rules. Another category are _data types_ (marked as `<<DataType>>`) that do not have an identity but attributes and possibly associations.

It's clear that features go to the `feature` table and data types to the `property` table. Object types, however, have an identity and, thus, cannot go to the `property` table but must be stored in `feature`. But since they are no features, we have this discussion about the table name. Btw, we already had this discussion for v4.

We currently have the following proposals:

1. Keep the name `feature`. In this case, we must clearly document that also non-feature object types are stored in this table. If we stick with `feature`, we should probably also rename `objectclass` (and related FK columns) to `featureclass` to be consistent.
2. Rename `feature` to `object`. This is the most generic solution but maybe too generic as pointed out by @muratkendir.
3. Rename `feature` to `cityobject`. This was the name in v4, so we could simply keep it. `cityobject` then should not be mistaken as reference to the CityGML class `AbstractCityObject` but understood in a more generic way: in the "city" db we store "city" objects.

Are there more proposals? Personally, I'm happy with either approach. We should just decide and make sure, the schema is consistent.

**Comment by yaozhihang** [comment]
I prefer the first proposal of @clausnagel. I also agree that using `feature` is much more common in GIS world mentioned by @muratkendir. Also, distinguisching `object` and `feature` sounds still GML specific.

**Comment by yaozhihang** [comment]
According to the offline discussion, we decided to keep the names `feature`, `objectclass` etc. having been used in the v5-alpha-1 release.
