### ISSUE TITLE
Drop the "aggregation_info" table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#127]
The `aggregation_info` table was used for automatically generating the delete and envleope functions for citydb v4. Since we have a relatively generic database schema in v5 and introduced the table `feature_hierarchy`,  we can also write a generic delete and envelope function and do not need the `aggregation_info` table anymore.

**Comment by muratkendir** [comment]
I think we don't need to create feature_hierarchy table, because we already defined feature-to-feature relations at the beginning of discussions about new database schema. At first stage, it was in feature_relation table, then we decided to move the data from feature_relation table into property table. So, i guess creating feature_hierarchy table will be only helpful for storing "isPartOf" (or Contains) type relation. By the way, if we decide to add namespace and name columns to feature_hierarchy table, then it will turn into again to feature_relation table, which is already capable of representing any type of hierarchical or bi-directional relation. What i am trying to explain is they looks very similar with feature_relation table. 

On the other hand, if we need envelope/aggregation functions for geometries/solids, i think we can re-evaluate the aggregation capability of postgis spatial functions (such as st_envelope or other Boundary Box functions), because i know some of them works very efficiently with spatial indexes (at least for 2D geometries, i am not sure about indexing performance of 3D geometries).

One more thing, if we really need to store automatically generated envelopes, boundary boxes or just feature aggregations, we should discuss about creating "materialized views", because they are not real data and can still efficiently response to queries. Of course we should investigate "Refresh Method" of materialized views before queries or after inserts.

**Comment by clausnagel** [comment]
The `aggregation_info` table in v4 is a pure metadata table storing the type of associations between UML classes and, thus, on an _abstract_ schema level. As @yaozhihang wrote, this information is required in v4 to be able to automatically generate the `del_*` and `env_*` functions especially for ADEs. The `feature_hierarchy` table has a different scope as it stores the _concrete_ hierarchy relations between features.

The question in this issue is whether we still need  `aggregation_info`. The idea (hope) is that we do not need to generate `del_*` and `env_*` functions anymore as we do it in v4, but that we can provide one function for each use case because the schema in v5 is much more generic. This new `delete` function could still query the `feature_hierarchy` table, for example, to decide whether a child of a given feature should be deleted as well (a child should not be deleted, for instance, if it is a top-level feature).

This dicussion about envelope/aggregation functions for geometry or materialed views is therefore out-of-scope. The `aggregation_info` table has been deleted for v5 alpha for the given reasons. So, closing this issue.
