### ISSUE TITLE
Rename objectid columns to object_id

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#131]
There is a naming inconsistency: "old" names from v. 4 use the _ to separate words in column names (which I like, for the sake of readability). These columns still exist.

New columns named "objectid" should be spelled IMO "object_id". Which is coherent with the old way, and looks nicer... ;-)

**Comment by muratkendir** [comment]
It is in address table, which is actually considered as feature in upgrade scripts. Yes, objectid should be rewritten as object_id, but also there are another things that we need to discuss. 
1) Do we really need to store address as a seperate table? Why? (Issue:  #105 ) 

2) "Object" is a definition for GIS objects, but the definition is a bit older. I remember that Esri group was naming OID or OBJECTID, but nowadays most of GIS softwares/brands (inc. Esri) preferring to use "feature" or "FID". I think we need to change all existing "object" definitions with "feature", so all definitions will be more clear and explicit. (Issue: #126 ) 
Note: I think object word was generally used for physical things, for phenomenons, but not for virtual things. Nowadays, while talking about GIS features, it is also referring to sensors, calculated/estimated locations, interpolated grids etc. For example, when we talking about the door number of a building in a database of any municipality, it doesn't mean exact location of the door object, rather than it is a virtual thing that shows proximate location of predefined entrance. 

3) Sometimes, i am feeling that similar "out-of-pattern" naming exists also for other column names too. For exp. "implicitgeom" (shorten implicit_geometry), datatype, classname, mimetype, codespace etc. On the other hand, namespace can be assumed as compund word, because it is already referenced in many resources. Maybe we can use wikipedia keyword search to specify and accept as compund word or not. It can be our standardization rule.

**Comment by clausnagel** [comment]
@muratkendir, thanks for your input. We should try to focus the discussion in each issue. So please move your comments on other questions to the corresponding issues. If there is no issue yet, feel free to open a new one.

**Comment by yaozhihang** [comment]
> There is a naming inconsistency: "old" names from v. 4 use the _ to separate words in column names (which I like, for the sake of readability). These columns still exist.
> 
> New columns named "objectid" should be spelled IMO "object_id". Which is coherent with the old way, and looks nicer... ;-)

@gioagu good point. The `objectid` is meant to be used for storing gml:id of CityGML features. Since currently all columns with the suffix `_id` are foreign key columns (e.g. the `objectclass_id` in feature table and `feature_id` in the property table), we choose the name `objectid` in order to avoid ambiguity.

**Comment by yaozhihang** [comment]
I would like to have a proposal:

Rename `objectid` -> `identifier` for the tables `feature`, `address`, `implicit_geometry` etc.
Rename the current `identifier` -> `global_identifier`
Rename the current `identifier_codespace` -> `global_identifier_codespace`

This allows to avoid inconsistent naming and also give a more clear meaning of the columns.

**Comment by gioagu** [comment]
Despite using the 3DCityDB for a number of years, I confess I never realised the subtle difference between gmlid column (without _) and all PK, FK with the _. ! :-)

Anyways, I like Yao's proposal of "identifier"!

**Comment by clausnagel** [comment]
Well, tbh, I was also not aware of this difference :smile: Must we really be that strict with our naming convention? Would developers really rely on the column name to understand whether the column is a FK?  

I'm fine with `objectid`, `featureid` or `resourceid` (used by WFS 2.0) and would also be happy with `object_id`, `feature_id` or `resource_id`.

I'm a bit hesitant with `global_identifier` though. Sounds like we would guarantee uniquness.

**Comment by yaozhihang** [comment]
> I'm a bit hesitant with `global_identifier` though. Sounds like we would guarantee uniqueness.

The idea is, the CityGML `identifier` values can directly go into this column, because they must be global unique according to the specification. If the attribute doesn't exist or the input format is e.g. GeoJSON, the importer should always fill that column with automatically generated UUID values in order to guarantee uniqueness.

**Comment by clausnagel** [comment]
> Maybe better also to add a unique constraint to that column.

This is exactly what I want to avoid, @yaozhihang . We already had this discussion and we must be able to store multiple versions of the same object, which means there will be duplicate identifiers.

**Comment by yaozhihang** [comment]
sorry, let me correct my text. I mean `featureId` here which should go into the `global_identifier` column. The CityGML `identifier` can be non-unique and going into the `identifier` column. The `identifier_codespace` column can keep as it is.
> The idea is, the CityGML identifier values can directly....

**Comment by clausnagel** [comment]
Just to avoid confusion:

| CityGML 3 CM | CityGML 3 GML encoding | Level of uniqueness | 
| ---  | --- | --- | 
| featureID | gml:id | dataset |
| identifier | gml:identifier | usually globally or within an application domain |

`gml:identifier` must have a `codespace`.

Both attributes are recommended to be (globally) unqiue but cannot forced to be. And I would like to avoid a unqiue constraint for both.

**Comment by yaozhihang** [comment]
This is a very nice overview table.

**Comment by yaozhihang** [comment]
Offline discussion: No changes needed.
