### ISSUE TITLE
How to purge/truncate a 3dcitydb?

### ISSUE THREAD

**Issue by do4sch** [3dcitydb/3dcitydb#14]
For testing purposes, we want to import several different citygml's into 3dcitydb.
We always have to delete the oracle user, and create a new 3dcitydb user using create_db.sql script.
Is there any script to purge/truncate an existing 3dcitydb-user?
I tried a general oracle script to disable all constraints, truncate all tables, and enable back the constraints.
After doing so, I wasn't able to connect to the user via Importer/Exporter Tool anymore...
Any hints?

best regards, Chris.

**Comment by FxKu** [comment]
You could use the DROP_DB.sql script. No need to drop the user. We have also designed a procedure called `cleanup_schema` in the `citydb_delete` package. It performs a delete on every table and resets the sequences. Since Oracle 12cR1 there's also the option to use TRUNCATE  ... CASCADE. This is what we also use in the PostgreSQL version and it's very fast no matter how big the DB is (around 15 sec). From the docs it seems that foreign key constraints need to be set to ON DELETE CASCADE. We also have a procedure for this called `update_schema_constraints` in the `citydb_util` package. So, you could try to write your own PLSQL function. For backwards compability reasons (to 11g) we will not change it for now.

**Comment by do4sch** [comment]
Great! That was what I am looking for.
So I can just call this cleanup procedure in sqlplus as
`exec citydb_delete.cleanup_schema` ?#
Thx for your support!

**Comment by FxKu** [comment]
Correct. Depending on the amount of data it would take a while, but if if your are testing with only small data sets it should be feasible.
