### ISSUE TITLE
Support ADE for Appearance and SurfaceData

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#157]
The current 3DCityDB v4 doesn't support ADE  for CityGML Appearance module. We could consider adding the ADE support for the new version v5. A good use case is that people can extend CityGML Appearance to support the [PBR](https://en.wikipedia.org/wiki/Physically_based_rendering) model via ADE. 

In order to support ADE for Appearance module, all Appearance/SurfaceData features should be registered in the `feature` table, and the columns `objectid`, `identifier`, and `identifier_codespace` can be removed from the `appearance` and `surface_data` tables.

**Comment by muratkendir** [comment]
I think we can consider Collada format as a reference point for this issue. Material library in Collada format is similar with X3D, but it supports more domains/applications than X3D. On the other hand, SFCGAL extension includes some tools which advances X3D (For exp: [st_AsX3D](https://postgis.net/docs/ST_AsX3D.html) ). Maybe we should also discuss about storing appearances/materials in XML(or JSON) format, since both of standards are XML based.

**Comment by clausnagel** [comment]
Well, at least the feature table would grow more quickly when additionally storing all appearances and surface data objects in this table. I haven't come across an ADE that extends the appearance classes in practice so far, but there could be one in the future, of course.

**Comment by yaozhihang** [comment]
According to the offline-discussion, we stick to the current structure.
