### ISSUE TITLE
Allow storing appearances of implicit geometries

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#158]
In CityGML 3.0, implicit geometries can have one or more appearances. This is not yet reflected in the current 3DCityDB v5 schema. 

An implicit geometry property of a feature is stored as row in `property`. In this row, we could of course also set the `val_appearance_id`. However, this would only allow to store a _single_ appearance but not _multiple_ ones. The implicit geometry object itself does not go into `feature` but is stored in `implicit_geometry`. The `implicit_geometry` table is not linked to `appearance`.

Possible solutions:
1. Each appearance property of the implicit geometry is stored as additional row in `property` and this row must reference the row storing the implicit geometry property as parent.
2. We add a `implicit_geometry_id` column to `appearance` to link both tables.

Maybe there are more possible solutions.

**Comment by clausnagel** [comment]
When thinking more about it, I guess solution 1) is not feasible. It would tightly link the appearances to the feature containing the implicit geometry at import time. But an implicit geometry is independent of a specific feature. So, the appearances must be linked to the implicit geometry instead as done in solution 2).

**Comment by muratkendir** [comment]
I think we can store multiple appearances for a single implicit geometry, since all related properties stored as different rows in property table. Similar to gml:name (or class) storage, all we need to increase index_number regarding to appearances for every implicit geometry instances.

**Comment by clausnagel** [comment]
Each row in `property` is related to a `feature` but the general implicit geometry and its appearances are not. Only the instantiation of an implicit geometry is feature-specific. So I think using the `property` is not feasible.

**Comment by muratkendir** [comment]
I checked again, you have right. Features can share same implicit_geometry instances, that's why we can not use features as a bridge/connector from appearances to implicit_geometries. We need to create a relation from appearance to implicit_geometries, which is shown in UML diagrams. [CoreDiagram](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/EQxsTLmqUVVOgbv-djt5R1QBNa98JzUf7sbIoX4IqEJh2g?e=rmulmS), [AppearanceDiagram](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/EfTx7vN3gLlBpehZe4YBv5cBM2_mEtyLSncDcGUeDb5YcA?e=A2P8oy)

**Comment by yaozhihang** [comment]
done with done with 8c0111d
