### ISSUE TITLE
Add unique constaint on the column "image_uri" for table "tex_image"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#173]
The image uri must be unique and non-null, since it is the key for referencing and sharing by the texture surface data. Also, the importer can make use of the `ON CONFLICT` clause to easily insert the data without needing to check the existence.

**Comment by clausnagel** [comment]
I'm not a fan of this proposal because of the following reasons:

- Just because two URIs are identical doesn't mean they reference the same texture image. This assumption applies, if at all, only to one and the same import operation.
- Storing a path to some local file system in the database doesn't seem very useful to me and might even be a security issue. For this reason, we only store the image name in `image_uri` for the 3DCityDB v4.
- When exporting, we even overwrite the image name with some generic but unique value because the original images names cannot be assumed to be unique.
- Similar to the discussion in #100, a unique constraint might hinder storing multiple versions of the same feature in the database.

To be honest, I don't even see value in storing the `image_uri` at all. I would even propose to drop it completely.

**Comment by yaozhihang** [comment]
@clausnagel good point. I also agree to drop the `image_uri` from the `tex_image` table

**Comment by yaozhihang** [comment]
let's close the ticket and feel free to open a new ticket to discuss if we need to drop the `image_uri` column.
