### ISSUE TITLE
Changes to objectclass table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#176]

**Comment by clausnagel** [comment]
1. swap objectclass id of Building and BuildingPart (also for Tunnel and Bridge)
2. Remove entries for CityObjectRelation and Role - they go into `property` not `feature`
3. Remove entry for ImplicitGeometry because it's stored in its own table not in `feature`
4. Add entry for TransportationComplex

**Comment by yaozhihang** [comment]
Agree, `CityObjectRelation` is just an association class and should be handled as a complex attribute mapped into the property table. Also, it has no ADE hooks and hence doesn't need to be linked with the objectclass table.

**Comment by thomashkolbe** [comment]
I also agree, `CityObjectRelation` is just an association class and should be handled as a complex attribute mapped into the property table.

**Comment by muratkendir** [comment]
> Add entry for TransportationComplex

TransportationComplex does not have a new successor class in CityGML 3.0. Most proper successor candidate class can be "AbstractTransportationSpace".

**Comment by clausnagel** [comment]
You are right, @muratkendir. I removed it from the list.

**Comment by yaozhihang** [comment]
Updated with [4386fe8](https://github.com/3dcitydb/3dcitydb/commit/4386fe8653feb5991433fcf9dc75375d514178c3)
