### ISSUE TITLE
Use Polygon or 3DBox data type for storing envelope?

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#184]
3DBox might be better. But the Oracle user guide doesn't recommend to use such kind of bbox. see the chapter 6.2.4
https://docs.oracle.com/en/database/oracle/oracle-database/21/spatl/coordinate-systems-concepts.html#GUID-A5727F9D-FA87-467F-851D-50B11A016460

**Comment by thomashkolbe** [comment]
If possible we should use a 3D bounding box / a 3D envelope, but it seems that Oracle Spatial does not offer such a geometry type. As Zhihang wrote, Oracle has the notion of a 3D BBOX, but not as a spatial datatype for geometries that can be stored - only to be used for 3D BBOX queries.

I would definitely not suggest to represent the 3D BBOX as a Solid, because that would require to create and deal with 6 surfaces for each feature.

Could you forward that question to our Oracle partners Hans Viehmann and/or to Mike Horhammer? Maybe they have a good recommendation.

However, we could also leave it as we had it before: using a slanted 3D polygon. If the real 3D volume is required, it can easily created using a function like this one: `SELECT sdo_geom_mbr(geom) INTO g FROM DUAL;`

**Comment by karinpatenge** [comment]
Hi,
I have shared your question with my colleagues in Development.
Let´s wait for their feedback.
Karin

**Comment by muratkendir** [comment]
I just want to remind that there are also additional functions called "SDO_MIN_MBR_ORDINATE" and "SDO_MAX_MBR_ORDINATE", which returns the minimum or maximum coordinate values in a given dimension. 
[ORACLE DOCS v21 -  sdo_max_mbr_ordinate](https://docs.oracle.com/en/database/oracle/oracle-database/21/spatl/SDO_GEOM-reference.html#GUID-19DF7A4F-9C7A-43FC-9E3B-5AC59050AA8D)

**Comment by clausnagel** [comment]
@karinpatenge, any news on this question? Otherwise we should stick with the slanted 3D polygon.

**Comment by karinpatenge** [comment]
Here is an example of a solid box:
`SDO_GEOMETRY(3008, NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1007,3), SDO_ORDINATE_ARRAY(1,1,1, 3,3,3)) `
There are no restrictions on storing the data as the box. If an SRID is specified, it must be one for a valid 3D CRS.

**Comment by clausnagel** [comment]
We decided offline to keep the 3D polygon for now as it does not require a valid 3D CRS like the solid box.
