### ISSUE TITLE
The need for "reference_type" table

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#193]
In the new property table, we have a new column called "val_reference_type". This column has to store integers and most probably refer to another table to distinguish reference types between features ( feature_id --> val_feature_id ). Bytheway there isn't any table proposal for it. So, my suggestion is to fill a new table called "reference_type" and fill this table with the well-known relation types in object-oriented languages. These well-known relation types could be as below:

[Table Contents](https://drive.google.com/file/d/15x2H52O5HOUb9d8FdpGWPVskiH8npwwt/view?usp=share_link)

To clarify my suggestion,  I am adding a sample data which is derived from a v4 --> v5 upgrade task (Relationship between former buildings and thematic_surface table). 

[Sample Rows for the relationship between building and thematic surfaces](https://drive.google.com/file/d/1oqWrsRjXcqswlSDC4WG3VxxmyPp7dPnx/view?usp=share_link)

The creation and insertion scripts for this table are shared below. If it doesn't make sense to you, then we may change the type for val_reference_type column from integer to text and use it as a standalone column.

```sql
CREATE TABLE citydb.reference_type
(
    id SERIAL PRIMARY KEY,
    typename text,
    is_bidirectional boolean
);
```
```sql
INSERT INTO citydb.reference_type 
	(id, typename, is_bidirectional)
VALUES 
	 (0,	'undefined',				false)
	,(1,	'generalization',			false)
	,(2,	'association',				true)
	,(3,	'aggregation',				false)
	,(4,	'composition',				false)
	,(5,	'directional_association',		false)
	,(6,	'association_class',			true);
```

**Comment by yaozhihang** [comment]
Hi @muratkendir, the `val_reference_type` column is acutally not new. It's earlier name is `val_feature_is_xlink` and its usage purpose has already been described in the documentation here:
https://github.com/tum-gis/3dcitydb-v5/blob/master/docs/docs/3dsteering/files/2021_10_19_3dcitydb_version_5-0_kolbe.xlsx

We renamed the column, because the word `xlink` sounds too GML specific.

**Comment by clausnagel** [comment]
The `val_reference_type` as defined and implemented has a different purpose than what you need. So, changing its meaning is not possible because we need the column with its current meaning.

We already have the `aggregation_info` table to store metadata about association types. Why not use this table and maybe have a proposal for extending it? And maybe you can share your use case for bi-directional associations? At least "all associations between model elements in the CityGML Conceptual Model are uni-directional." (see chapter 5.2 of the CityGML 3.0 CM specification).

**Comment by yaozhihang** [comment]
let's take a simple example: suppose we have two buildings with id `1` and `2`, and the two buildings are related with each other. The feature and property table will look like this:

**FEATURE Table**
|id|objectclass_id|...|
|--|--|--|
|1|901|...|
|2|901|...|

**PROPERTY Table**
|name|namespace_id|feature_id|val_feature_id|...|
|--|--|--|--|--|
|relatedto|0|1|2|...|
|relatedto|0|2|1|...|

By using the objectclass id, property name and namespace, it is possible to look up the `aggregation_info` and `objectclass` tables and query, whether the `relatedTo` of two buildings  is an aggregation/composition or not (normal association).
