### ISSUE TITLE
High number of export files

### ISSUE THREAD

**Issue by sehHeiden** [3dcitydb/3dcitydb#199]
I am currently tring to export three different tiles from a citygml (LoD2) to glb. Currently a single .gltf or .glb. per building is exported in a folder structure *0/0/number/buildingID.gltf* is exported although tiling is not activated.
- Is it possibleto export a single file.
- is there some experience in the combination with the master portal?

**Comment by thomashkolbe** [comment]
Note, that in order to visualize the glTF output files (tiled or untiled), the 3DCityDB web map client must be used. I don't think that the vanilla CesiumJS code supports the loading of our files. The 3DCityDB web map client has specific extensions, which I guess, are not available within the masterportal.

However, there is another open source project called "py3Dtilers" that directly connects to a 3DCityDB and is able to produce 3Dtiles datasets. These can be directly consumed by any CesiumJS based viewer. Hence, it should work with the masterportal. The project can be found here: https://github.com/VCityTeam/py3dtilers

**Comment by BWibo** [comment]
For common tasks like moving files to a server or network share, that can take very long with many small files, I can recommend to create some kind of archive (`zip`, `tar.gz`, `7z`, or any other), move the file to the server and extract it locally on the target system using SSH.

**Comment by sehHeiden** [comment]
Thanks. 
I also found a parameter to exclude buildings in citygml-tiler working well.
I can manually correct the offset, too. So hence I can not set it to sea level but hat least on the ground.
I think, this thread can be closed.

I would just like to kindly ask to link to py3dtilers, because I never found this by my own.

**Comment by thomashkolbe** [comment]
Good point, we will add a link to py3dtilers to the homepage (we have to update it anyway).
