### ISSUE TITLE
Latest Postgres, PostGIS and SFCGAL support

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/3dcitydb#232]
Hey all,

quite some time passed since the last release of 3DCityDB. Meanwhile, there are new Postgres, PostGIS and SFCGAL versions available. It would be nice to have these versions in our Docker images. 
Especially, the new SFCGAL versions (>1.3.x) are interesting, as they may (I have not tested if this is really the case) resolve issues with planarity checks for basic functionality like area and volume computation.
For testing you can use the images from my 3DCityDB fork:
https://github.com/BWibo/3dcitydb/pkgs/container/3dcitydb-pg
E.g. `docker pull ghcr.io/bwibo/3dcitydb-pg:latest-alpine` comes with PostGIS 3.4 and SFCGAL 1.4.1.

Actually, everything is set to have this. All we need is a 3DCityDB release, so the images get cleanly rebuilt from the workflows.
@clausnagel @yaozhihang @thomashkolbe Can we release `v4.4.1` just to update the images?
Are there maybe some other small changes, we can include in a small maintenance release?

**Comment by thomashkolbe** [comment]
It would be good, if new Docker images with the updated PostGIS (and especially SFCGAL version) would be provided. The older versions (and especially the PostGIS/SFCGAL version) that are currently being used by our official Docker images suffer from a nasty bug in the ST_IsPlanar() function in SFCGAL version 1.3.X. This is explained here: https://gis.stackexchange.com/questions/447491/why-is-this-polygon-not-planar-for-postgis

I have tested the updated container image and can confirm that now most polygons of the 3D city model of Munich (taken from the official Open Data LOD2 models of Bavaria) are recognized as planar (but unfortunately not all of them). The problem with polygons not being considered as planar by PostGIS/SFCGAL is that functions like ST_3DArea() or ST_Volume() will not work, but break the evaluation of the query with an error message. These functions run internally a test, if the polygons provided in the input geometry are planar, before the computation of the surface area or volume respectively is carried out. Unfortunately, it is also not possible to simply run the ST_Tessellate() function on the as non-planar detected polygons before in order to triangulate such polygons, because also ST_Tesselate() makes the planarity check first. It seems that there is no tolerance value that could be set for the planarity checks in PostGIS+SFCGAL.

**Comment by clausnagel** [comment]
Hi @BWibo, please open a PR with the required changes. We are currently planning a September release which mostly focuses on bugfixes and changes for the Importer/Exporter. We can surely include a patch version of the 3DCityDB with your proposed change.

**Comment by BWibo** [comment]
Resolved in fb7df7c24f977f21b9553895136549ce30beea9b, #207 

@clausnagel @yaozhihang @thomashkolbe 
I managed to build and push the images locally, so we could avoid a release and the effort for a lot of people, that comes with it. The new images are now available from [Github container registry](https://github.com/3dcitydb/3dcitydb/pkgs/container/3dcitydb-pg) and [Dockerhub](https://hub.docker.com/r/3dcitydb/3dcitydb-pg/tags).

The recommended version with latest dependencies is: `latest-alpine` --> `16-3.4-4.4.0-alpine`. It comes with 
geos=3.12.2, gdal=3.9.1, proj=9.4, and sfcgal=1.5.1.

A summary of the other Docker related changes can be found here: #207
I updated the changelog and added a hint in the docs regarding the different dependency versions in the base images:
https://3dcitydb-docs.readthedocs.io/en/latest/3dcitydb/docker.html#postgresql-postgis-images

**Comment by lbartoletti** [comment]
> It would be good, if new Docker images with the updated PostGIS (and especially SFCGAL version) would be provided. The older versions (and especially the PostGIS/SFCGAL version) that are currently being used by our official Docker images suffer from a nasty bug in the ST_IsPlanar() function in SFCGAL version 1.3.X. This is explained here: https://gis.stackexchange.com/questions/447491/why-is-this-polygon-not-planar-for-postgis
> 
> I have tested the updated container image and can confirm that now most polygons of the 3D city model of Munich (taken from the official Open Data LOD2 models of Bavaria) are recognized as planar (but unfortunately not all of them). The problem with polygons not being considered as planar by PostGIS/SFCGAL is that functions like ST_3DArea() or ST_Volume() will not work, but break the evaluation of the query with an error message. These functions run internally a test, if the polygons provided in the input geometry are planar, before the computation of the surface area or volume respectively is carried out. Unfortunately, it is also not possible to simply run the ST_Tessellate() function on the as non-planar detected polygons before in order to triangulate such polygons, because also ST_Tesselate() makes the planarity check first. It seems that there is no tolerance value that could be set for the planarity checks in PostGIS+SFCGAL.

👋Hi there!

As a SFCGAL developer and former urban planner, I'm really glad to see SFCGAL being used for 3D city modeling! For the planarity issues, you should indeed try partitioning using CG_Triangulate rather than Tessellate. If you still have issues with CG_Triangulate, please open a ticket on our GitLab - we'd be happy to help troubleshoot. A small sample dataset showing the non-planar polygons would be helpful.

Just a note: from PostGIS 3.5 onwards, SFCGAL functions will use the CG_ prefix (like CG_Triangulate), while ST_ prefix will be reserved for standard PostGIS functions.
