### ISSUE TITLE
Separating indexes and DB schemas into different SQLs

### ISSUE THREAD

**Issue by stirringhalo** [3dcitydb/3dcitydb#6]
I'm doing large fills (currently 250k buildings) of 3DCityDB from wavefront OBJ files in a custom reader into Postgres. As part of this, I drop all indexes ahead of time (except for the primary key ones).

It'd be great to have the CREATE_DB.sh script separate db and index building into different scripts so it would be easy to rebuild them on demand.

**Comment by clausnagel** [comment]
We use [pgModeler](http://www.pgmodeler.com.br/) as main tool for designing the 3DCityDB schema under PostgreSQL and for automatically exporting it to an SQL script file. We wanted to minimize any pre or post processing outside pgModeler as much as possible. That's why there is no separate `CREATE_INDEX.sql` script at the moment.

For batch imports, we have good experience with just dropping the main spatial indexes. The function `citydb_pkg.drop_spatial_indexes()` is useful here. When using the [importer/exporter](https://github.com/3dcitydb/importer-exporter) tool, dropping normal indexes may even slow down the import as they are needed for resolving CityGML XLinks (e.g. when importing appearance information).

**Comment by stirringhalo** [comment]
Makes sense about the sluggishness with appearances. I'll just do the index dropping + re-add manually.
