### ISSUE TITLE
Cast building surface projection polygon to building table?

### ISSUE THREAD

**Issue by AndreM84** [3dcitydb/3dcitydb#73]
Dear 3dcitydb team,

I use a large data set of CityGML 3d building models (LoD2) for spatial analyses where most of the time a footprint or 'birds view projection' in 2d is suffiecient to calculate areas and distances among others. My DB is a postgresql/postgis with a 3dcitydb set up.

For my purposes I wrote postgresql queries which:

- transform all 3d surface geometries from surface_geometry table to two 2d with `st_force2d()`
- union all geoemtries belonging to the same surface_geometry.root_id which corresponds to the building.id with a `group by` query on the surface_geometry.root_id and `st_union()` 
- combine the building table and the 2d surface projection which is the query result from the above mentioned steps

Do you see more ressoruce (cpu, memory, db-processing time) efficient ways to cast footprint/projection geometries to the table building to allow easily running other spatial and non spatial analyses on the dataset (most of these were developed using 2d shapefile data).

` version()` and 
` postgis_full_version()` give  

> PostgreSQL 13.2, compiled by Visual C++ build 1914, 64-bit

and
> POSTGIS="3.1.1 3.1.1" [EXTENSION] PGSQL="130" GEOS="3.9.1-CAPI-1.14.1" PROJ="7.1.1" GDAL="GDAL 3.2.1, released 2020/12/29" LIBXML="2.9.9" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.5.0 (Internal)" RASTER

respectively.
The 3dcityDB is 4.1.0 on the virtual machine with postgres/postgis-versions shown above. On a local machine it is 4.0.3 and cma ewith the importer/exporter version 4.2.3.

**My Queries**
[20211201_GithubQuestion_CastGeomToBuildingQueries.txt](https://github.com/3dcitydb/3dcitydb/files/7635193/20211201_GithubQuestion_CastGeomToBuildingQueries.txt)

**Sample CityGML LoD2 data** could be downloaded from the German Federal Agency for Cartography and Geodesy ([here](https://sg.geodatenzentrum.de/web_public/gdz/testdaten/LoD2-DE-utms-citygml.zip)).

Thanks in advance for any comments and best regards
André

**Comment by thomashkolbe** [comment]
In CityGML most LOD2 models have semantic boundary surfaces. For the 3D building models in LOD2 produced by German mapping agencies this is a requirement. This means that all surfaces are classified as being a "WallSurface", "RoofSurface", "GroundSurface" etc. 

Since you are looking just for the building footprints, the easiest way is to join the BUILDING table with the THEMATIC_SURFACE table (which ensures that only thematic surfaces from buildings are selected and not also from tunnels or bridges etc.). In the same query only select those tuples (using "AND"), where the column OBJECTCLASS_ID is equal to 35 (which means "GroundSurface"). See the online documentation https://3dcitydb-docs.readthedocs.io/en/release-v4.1/3dcitydb/schema/module/building.html and scroll down to the headline "THEMATIC_SURFACE". From the resulting tuples the column "LOD2_MULTI_SURFACE_ID" has the foreign key to the SURFACE_GEOMETRY table where you then can directly take the geometry. 

Note that CityGML LOD2 datasets can be a structured in a way that one semantic "GroundSurface" object of a building is associated with multiple polygons (MultiSurface). In this case you will have to collect all single polygons from the SURFACE_GEOMETRY table that belong to the same CityGML GroundSurface object. This can easily be done by selecting all tuples from the SURFACE_GEOMETRY table where the GEOMETRY column is not null and where the ROOT_ID is equal to the ID of the column "LOD2_MULTI_SURFACE_ID" from the table THEMATIC_SURFACE.

Both queries described above can be expressed as just a single query having two joins: 1) BUILDING.ID with THEMATIC_SURFACE.BUILDING_ID, and 2) THEMATIC_SURFACE.LOD2_MULTI_SURFACE_ID with SURFACE_GEOMETRY.ROOT_ID. You could aggregate the resulting tuples by SURFACE_GEOMETRY.ROOT_ID and construct MultiPolygons using the appropriate spatial SQL operator.

Hope this helps. Best regards
Thomas Kolbe

**Comment by AndreM84** [comment]
Dear Prof. Kolbe,

thank you for your response and help. I am sorry for updating this issue so lately, but my immediate response was not saved to github for whatever reason.

I definitely did not reflect the Multi-Surface construction of the CityGML data suffinciently in my SQL code (which alraedy was adapted to include the THEMATIC_SURFACE table, but still was not working adequately). Your proposals how to bind both, THEMATIC_SRUFACE and SURFACE_GEOMETRY data to the building table works fine and solves my problem. Since there is no spatial/postgis operation needed (or only few when joining building parts of a building), I assume that the processing time will be acceptable running the query on the whole data set)

However, I will have to check if it makes more sense to me to work with building parts and their specific attributes (e.g. roof type or building height) or focus on building level analyses where I either have to add a statistical descritpion (e.g. x% of the roof is roof type A, 1-x% have is type B) or follow a principle of dominant building parts (that means the attributes of the biggest building part determines the buildings attributes). In any case your answer was very helpfull!

(For documentation purposes the PostgreSQL-queries are attached)
[20211230_issue73_response.txt](https://github.com/3dcitydb/3dcitydb/files/7827987/20211230_issue73_response.txt)
