### ISSUE TITLE
PostGIS 3 compatibility ?

### ISSUE THREAD

**Issue by MaelREBOUX** [3dcitydb/3dcitydb#75]
Hello,

The requirements indicates :

> PostgreSQL DBMS >= 9.6 with PostGIS extension >= 2.3

But as PostGIS 3 is a major (huge) upgrade and could brings compatibility issues. Could you please enhance the requirements to clearly indicates that it is compatible or not.

Nowadays, a standard configuration is, I think,  PostgreSQL 13 + PostGIS 3.1

Thank you for your precisions.

**Comment by FxKu** [comment]
If you check the docker images you see it also runs with PostGIS 3 - and of course everybody should be using that by now :smiley: 2.3 is just the minimal supported version, hence the `>=`. It should also run on a newer Postgres release since there were so many PostGIS-related improvements introduced in recent years.

**Comment by MaelREBOUX** [comment]
Thank you for the answer.

> If you check the docker images you see it also runs with PostGIS 3 

Sorry : I do not use Docker

> 2.3 is just the minimal supported version, hence the >=

Sure but from my experience some things may work great with PostGIS >= 2.3 but crash with PostGIS 3.x. Because v3 is a major step. That was the goal of my question.

Meanwhile : I now run a 4.2.0 DB on PG 13 + PostGIS 3.1 and all seems to works well. Until now ;)
