### ISSUE TITLE
What is the purpose of the Thematic_Surface table?

### ISSUE THREAD

**Issue by walterogrady** [3dcitydb/3dcitydb#8]
What is the purpose of the thematic_surface table when the building geometry can be represented using the building table's own geometry attributes?

I read the documentation but it's not clear to me. Is there a simple example of when one is used instead of the other?

**Comment by clausnagel** [comment]
The database schema follows the CityGML data model. In CityGML, a building's outer shell can be represented as volume or multi-surface geometry using the spatial properties of the `Building` feature type (e.g., `lod2Solid` or `lod3MultiSurface`). Such a geometry representation provides the 3D shape, extent, and location of the building but no information about the meaning of the separate parts of the geometry. For instance, it is not explicit which surface of the geometry is a roof, a wall, or a ground surface of the building. 

For this reason, CityGML defines the feature types `RoofSurface`, `WallSurface`, `GroundSurface`, etc. These features are used to semantically classify the different boundary surfaces of the building's outer shell. And they also have spatial properties to represent the shape, extent and location of a wall, roof, or ground surface. So when modelled, these features enrich the semantic information about the building and support more sophisticated queries and analyses. 

Note that both ways of describing the building are complementary and not mutually exclusive. If you just have a geometric representation of the building without knowing which parts are roofs or walls, then simply assign the geometry as-is to the `Building` feature. If you have more knowledge about roof and wall surfaces, then represent these parts as `RoofSurface` or `WallSurface` features and assign them to the `Building`. CityGML is very flexible and supports models ranging from simple geometric models to semantically rich models. There is a great paper on this so-called [spatio-semantic coherence](http://www.isprs.org/proceedings/XXXVI/2-C43/Session1/paper_Stadler.pdf). 

Most of the LoD2 building models produced today both semantically describe the wall, roof and ground surfaces and provide a solid geometry of the outer shell in addition. The semantic entities are used to query and process the separate parts of the building. The solid geometry is useful for geometric calculations such deriving the building's volume. Since the geometry of a wall or roof surface will be identical to a part of the solid geometry, the CityGML specification requires that the geometry of boundary surfaces must not be given redundantly in a dataset but that they shall reuse the surfaces of the building's geometry by reference (using GML's XLink mechanism). A nice CityGML example dataset demonstrating this can be found [here](http://schemas.opengis.net/citygml/examples/2.0/building/Building_LOD2-EPSG25832.gml).

Coming to the 3DCityDB finally: the table `THEMATIC_SURFACE` is used to store the semantic boundary surfaces of the building, whereas the spatial columns of the `BULIDING` table are used to store the purely geometric representation. Use the Importer/Exporter tool to import the above mentioned dataset into the 3DCityDB - then you can learn how the geometries go into the different tables and how the XLink references are mapped on the database level.

Sorry for the lengthy answer - I hope this helps.

Cheers,
Claus

**Comment by walterogrady** [comment]
Thank you Claus.
