### ISSUE TITLE
Deside which columns should be indexed in 3dcitydb v5

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#97]
It is currently not clear, which columns (especially in the `feature` and `property` tables). We have to decide it for the Alpha release.

**Comment by muratkendir** [comment]
- Yes i agree that we need to create indexes for all columns starting "val_" prefix.
- Yes, all foreign keys should be also indexed. Actually by saying used together with "ON", i was meaning same thing.
- PostgreSQL creates these suffixes automatically by selecting default index types, but i prefer to use also "index_types", because some times it can be differ regarding to usage of indexed column. For example, let's assume we have a huge table, which must be indexed with default method "B-Tree", but we don't have sufficient storage for that. In this kind of situation, you may decide to use BRIN indexes and you wouldn't have any indicator that specifies index type. Also there are other possibilities regarding to full-text-search etc.
[link to index types in postgresql](https://drive.google.com/file/d/15Eb4IGm5graRaHF9IApD3kkZiQ17kT1U/view?usp=sharing)
-- In the meantime, if you want to be keep naming convention for indexes as default way, i will find it reasonable. It is not a mandatory on my side.
- About index names more than 30 characters, yes it can be very serious issue on Oracle side, i need to check that.

**Comment by clausnagel** [comment]
Closing since this has been solved as far as I understand. Re-open on demand.
